DDCE-3738 Update the CSP policy
hmrc/tax-history-frontend pull request #333
Opened 2023-03-31 09:08 UTC by mywyau

![Screenshot 2023-03-31 at 10 03 45](https://user-images.githubusercontent.com/47248104/229077643-9aa4e3cb-503e-4313-9215-135383da314b.png)

2023-03-31 11:00 UTC, mywyau commented
Unit and ATs should still pass

<img width="1742" alt="Screenshot 2023-03-31 at 12 00 24" src="https://user-images.githubusercontent.com/47248104/229103055-ace70169-37d1-4175-bc4c-73e36e2045fe.png">

2023-04-05 08:36 UTC, frikit requested changes
- Please update dependencies

2023-04-05 08:36 UTC, frikit commented on app/views/govuk_wrapper.scala.html
> +)(mainContent: Html)(implicit request: Request[_], requestHeader: RequestHeader, messages: Messages, appConfig: config.AppConfig)
please remove `requestHeader: RequestHeader` as not used anywhere

2023-04-11 08:08 UTC, frikit requested changes
- update all deps

2023-04-11 08:08 UTC, frikit commented on app/config/FeatureSwitching.scala
> +  def setValue(featureSwitch: FeatureSwitch, value: String): SystemProperties =
we never supported changing config values from code and I dont see a need here as well, please delete all `setValue` , `enable`, `disable`, `fsGuard`

2023-04-11 08:08 UTC, frikit commented on app/config/FeatureSwitching.scala
> +trait FeatureSwitching {
I would say this class is too much for current use case, you can just add a method inside your impl like `StudentLoanFlagFeature` and trigger that one, you can add all required info like type class in there and method can be generic in interface like getValue[A] and should be simple and good enough to use it

2023-04-11 08:08 UTC, frikit commented on test/controllers/EmploymentDetailControllerSpec.scala
> +        c.getEmploymentDetails(employmentId.toString, taxYear)(fakeRequest.withSession("USER_NINO" -> nino))
revert back name here to be more descriptive

2023-04-11 08:08 UTC, frikit commented on test/controllers/EmploymentDetailControllerSpec.scala
> +        c.getEmploymentDetails(employmentId.toString, taxYear)(fakeRequest.withSession("USER_NINO" -> nino))
in this class

2023-04-11 08:08 UTC, frikit requested changes
- update all deps

2023-04-11 12:29 UTC, mywyau commented
Old Coverage
![Uploading Screenshot 2023-04-11 at 13.28.35.png…]()

2023-04-11 14:34 UTC, mywyau commented
**New code coverage**
![Screenshot 2023-04-11 at 15 34 17](https://user-images.githubusercontent.com/47248104/231196764-b923e6bc-08c5-405f-9ff3-7dc681f4e227.png)

2023-04-11 15:11 UTC, mywyau commented
- Reverted to remove feature switch class
- Updated dependencies 
- Improved test coverage, adding in more tests.

2023-04-12 08:25 UTC, frikit approved these changes

2023-04-12 08:25 UTC, merged